2022-09-11 15:14:07,384 : INFO : root : Loading config.
2022-09-11 15:14:07,388 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-09-11 15:14:07,388 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\a6762098cb994b55cb03a478b26022ee.mpf_cache
2022-09-11 15:14:07,458 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\9cf7ccc27b21f4d6162237fadfc53e5a.mpf_cache
2022-09-11 15:14:07,458 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\c215df352878fee5d54f1a5ec5b16e7c.mpf_cache
2022-09-11 15:14:07,459 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\abaa92c43d134e3392cbb2346e6a16be.mpf_cache
2022-09-11 15:14:07,460 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\fc46d53fcb9fe6b8abf783d9c813390a.mpf_cache
2022-09-11 15:14:07,461 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2022-09-11 15:14:07,461 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2022-09-11-15-14-07-mpf-DESKTOP-7HNFDQ5.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2022-09-11 15:14:07,461 : INFO : Machine : MPF path: c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf
2022-09-11 15:14:07,461 : INFO : Machine : Machine path: c:\trashland_2
2022-09-11 15:14:07,461 : INFO : Machine : Platform: win32
2022-09-11 15:14:07,461 : INFO : Machine : Python executable location: c:\users\tanner\appdata\local\programs\python\python37\python.exe
2022-09-11 15:14:07,461 : INFO : Machine : Python version: 3.7.8 (64-bit)
2022-09-11 15:14:07,463 : INFO : Machine : Initialise MPF.
2022-09-11 15:14:07,744 : INFO : FAST : Connecting to com20 at 921600bps
2022-09-11 15:14:07,746 : INFO : Machine : Shutting down...
2022-09-11 15:14:07,746 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2022-09-11 15:14:07,858 : ERROR : Machine : Failed to initialise MPF
Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\fast\fast.py", line 311, in _connect_to_hardware
    await comm.connect()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 45, in connect
    await self._connect_to_hardware(self.port, self.baud, self.xonxoff)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 54, in _connect_to_hardware
    self.reader, self.writer = await connector
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\clock.py", line 155, in open_serial_connection
    **kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\asyncio\coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\serial_asyncio\__init__.py", line 410, in create_serial_connection
    ser = serial.serial_for_url(*args, **kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\serial\__init__.py", line 90, in serial_for_url
    instance.open()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'com20': PermissionError(13, 'Access is denied.', None, 5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 673, in initialise_mpf
    raise init.exception()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 244, in initialise
    await self.initialise_core_and_hardware()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 240, in initialise_core_and_hardware
    await self._initialize_platforms()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 331, in _initialize_platforms
    result.result()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\fast\fast.py", line 178, in initialize
    await self._connect_to_hardware()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\fast\fast.py", line 315, in _connect_to_hardware
    "port".format(port), 1, self.log.name) from e
mpf.exceptions.runtime_error.MpfRuntimeError: Runtime Error in FAST: Could not open serial port com20. Check if you configured the correct port in the fast config section and if you got sufficient permissions to that port Error Code: RE-FAST-1 (https://docs.missionpinball.org/en/0.55/logs/RE-FAST-1.html)
2022-09-11 19:07:18,196 : INFO : root : MPF run loop ended.
