2022-10-17 07:28:06,640 : INFO : root : Loading config.
2022-10-17 07:28:06,643 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2022-10-17 07:28:06,644 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\a6762098cb994b55cb03a478b26022ee.mpf_cache
2022-10-17 07:28:06,716 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\9cf7ccc27b21f4d6162237fadfc53e5a.mpf_cache
2022-10-17 07:28:06,717 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\c215df352878fee5d54f1a5ec5b16e7c.mpf_cache
2022-10-17 07:28:06,718 : WARNING : ConfigProcessor : Config file in cache changed: c:\trashland_2\modes\base\config\base.yaml
2022-10-17 07:28:06,718 : INFO : ConfigProcessor : Loading config from file c:\trashland_2\modes\base\config\base.yaml.
2022-10-17 07:28:06,731 : INFO : ConfigProcessor : Loading config: c:\trashland_2\modes\base\config\base.yaml
2022-10-17 07:28:06,732 : INFO : ConfigProcessor : Config file cache created: C:\Users\Tanner\AppData\Local\Temp\708062243e0edcfa77dd6b1521bd0d4e.mpf_cache
2022-10-17 07:28:06,733 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\c4174472f67f7b070dd6fb437c6feb0c.mpf_cache
2022-10-17 07:28:06,737 : INFO : ConfigProcessor : Loading config from file c:\trashland_2\modes\attract\shows\.\attract_display_loop.yaml.
2022-10-17 07:28:06,748 : INFO : ConfigProcessor : Loading config: c:\trashland_2\modes\attract\shows\.\attract_display_loop.yaml
2022-10-17 07:28:06,748 : INFO : ConfigProcessor : Config file cache created: C:\Users\Tanner\AppData\Local\Temp\9e6b4d5e43fd00e219ba7c739d818ad6.mpf_cache
2022-10-17 07:28:06,749 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\abaa92c43d134e3392cbb2346e6a16be.mpf_cache
2022-10-17 07:28:06,754 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\fc46d53fcb9fe6b8abf783d9c813390a.mpf_cache
2022-10-17 07:28:06,758 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\b46de592c65b9a27a1f4965daee53c91.mpf_cache
2022-10-17 07:28:06,763 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\5b50cb1d58cd4116013cda74c2923169.mpf_cache
2022-10-17 07:28:06,769 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\2734ac1662e5e62f2e4cb2a8d902a8f2.mpf_cache
2022-10-17 07:28:06,776 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\fe169133106b4804e097dca6b78afaf5.mpf_cache
2022-10-17 07:28:06,780 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\d4f531e94c6a484dd08e4121f6e3a74e.mpf_cache
2022-10-17 07:28:06,785 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\e9c431c8aa2f7ab7b37617b37185d68f.mpf_cache
2022-10-17 07:28:06,790 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Tanner\AppData\Local\Temp\07112933e6abcdb1819075df64aee3c0.mpf_cache
2022-10-17 07:28:06,795 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2022-10-17 07:28:06,795 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2022-10-17-07-28-06-mpf-DESKTOP-7HNFDQ5.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2022-10-17 07:28:06,795 : INFO : Machine : MPF path: c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf
2022-10-17 07:28:06,795 : INFO : Machine : Machine path: c:\trashland_2
2022-10-17 07:28:06,795 : INFO : Machine : Platform: win32
2022-10-17 07:28:06,795 : INFO : Machine : Python executable location: c:\users\tanner\appdata\local\programs\python\python37\python.exe
2022-10-17 07:28:06,795 : INFO : Machine : Python version: 3.7.8 (64-bit)
2022-10-17 07:28:06,797 : INFO : Machine : Initialise MPF.
2022-10-17 07:28:07,024 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,072 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2022-10-17 07:28:07,072 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,072 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.8', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19041-SP0', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19041', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2022-10-17 07:28:07,073 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2022-10-17 07:28:07,113 : INFO : EventManager : Event: ======'drop_target_bank_single_main_up'====== Args={}
2022-10-17 07:28:07,113 : INFO : EventManager : Event: ======'drop_target_bank_mid_up'====== Args={}
2022-10-17 07:28:07,114 : INFO : EventManager : Event: ======'drop_target_bank_right_up'====== Args={}
2022-10-17 07:28:07,123 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2022-10-17 07:28:07,127 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...pdate,queue')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...pdate,queue')>)>
Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 728, in _queue_task_done
    future.result()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\mode_controller.py", line 101, in initialise_modes
    **item.kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 132, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 104, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 126, in _parse_config
    return self.get_full_config(config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 199, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 180, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 222, in _validate_config
    validation_failure_info=ValidationPath(validation_failure_info, k))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 259, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 709, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 401, in _validate_type_enum
    item, str(param)))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 728, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'attract_display_loop': None, 'tl2-ch-color-wheel-cw-ccw-show-Set': {'speed': 40}} >> Config validation error: Entry show_player:show_player:action = "attract_display_loop" is not valid. Entry "attract_display_loop" is not valid for enum. Valid values are: play,stop,pause,resume,advance,step_back,update,queue Error Code: CFE-ConfigValidator-5 (https://docs.missionpinball.org/en/0.55/logs/CFE-ConfigValidator-5.html)
2022-10-17 07:28:07,166 : INFO : Machine : Starting the main run loop.
2022-10-17 07:28:07,169 : INFO : Machine : Shutting down...
2022-10-17 07:28:07,169 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2022-10-17 07:28:07,170 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 728, in _queue_task_done
    future.result()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\mode_controller.py", line 101, in initialise_modes
    **item.kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 132, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 104, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 126, in _parse_config
    return self.get_full_config(config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 199, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 180, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 222, in _validate_config
    validation_failure_info=ValidationPath(validation_failure_info, k))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 259, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 709, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 401, in _validate_type_enum
    item, str(param)))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 728, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'attract_display_loop': None, 'tl2-ch-color-wheel-cw-ccw-show-Set': {'speed': 40}} >> Config validation error: Entry show_player:show_player:action = "attract_display_loop" is not valid. Entry "attract_display_loop" is not valid for enum. Valid values are: play,stop,pause,resume,advance,step_back,update,queue Error Code: CFE-ConfigValidator-5 (https://docs.missionpinball.org/en/0.55/logs/CFE-ConfigValidator-5.html)
2022-10-17 07:28:23,636 : ERROR : root : 
Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 728, in _queue_task_done
    future.result()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\mode_controller.py", line 101, in initialise_modes
    **item.kwargs)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 132, in process_mode_config
    config = self.validate_config(config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 104, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\config_players\device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 126, in _parse_config
    return self.get_full_config(config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_player.py", line 199, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 180, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 222, in _validate_config
    validation_failure_info=ValidationPath(validation_failure_info, k))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 259, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 709, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 401, in _validate_type_enum
    item, str(param)))
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\config_validator.py", line 728, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'attract_display_loop': None, 'tl2-ch-color-wheel-cw-ccw-show-Set': {'speed': 40}} >> Config validation error: Entry show_player:show_player:action = "attract_display_loop" is not valid. Entry "attract_display_loop" is not valid for enum. Valid values are: play,stop,pause,resume,advance,step_back,update,queue Error Code: CFE-ConfigValidator-5 (https://docs.missionpinball.org/en/0.55/logs/CFE-ConfigValidator-5.html)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\commands\game.py", line 239, in __init__
    self.machine.run()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 687, in run
    self._run_loop()
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 772, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "c:\users\tanner\appdata\local\programs\python\python37\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
